PSLmodels/Cost-of-Capital-Calculator

MANIFEST.in

This PR has minor changes to MANIFEST.in to make sure the included files are installed.

changes to MANIFEST.in for file inclusion

---

btax/__init__.py

Small edit that can be merged at any time, this PR makes `_version` be imported to `btax` so you can do:
```
import btax
btax._version.get_versions()
```

Versioneer edit

---

btax/calc_z.py
btax/data/depreciation_rates/BEA_IRS_Crosswalk.csv
btax/data/depreciation_rates/Economic Depreciation Rates.csv
btax/param_defaults/btax_defaults.json
btax/param_defaults/btax_results_by_asset.json
btax/param_defaults/btax_results_by_industry.json
btax/parameters.py
btax/read_bea.py
btax/run_btax.py
btax/visuals.py

This PR includes updates to the jsons that inform the formatting of the output tables.  It also makes progress towards a cleaner visualization of the output.

Update visual output, jsons

---

btax/visuals_plotly.py

adds an additional plotting function.

add alt plotting function

---

btax/btax_reform_run.py
btax/param_defaults/btax_defaults.json

should have been fraction of interest *not* deductible

fix typo in int haircut description

---

btax/parameters.py

update some parameters to be CBO (2014) values

Update some hardcoded parameter values

---

btax/calc_z.py
btax/parameters.py

Fixes the equation for the NPV of depreciation deductions that are at the rate of economic depreciation.

Small fixes to calc with econ depreciation

---

btax/calc_final_outputs.py
btax/run_btax.py

The by industry output tables were not reporting correctly because of a bad join between two data frames.  This PR fixes that.

Fix by industry output

---

btax/param_defaults/btax_defaults.json
btax/param_defaults/btax_results_by_asset.json
btax/param_defaults/btax_results_by_industry.json
btax/tests/test_params_have_effect.py

This PR updates the default values json to include notes for the hover over information for the table headers on the CCC UI

Include text for hover over buttons on web app

---

btax/calc_final_outputs.py
btax/get_taxcalc_rates.py

This PR updates the calculation of the marginal tax rate on non-corporate income to account for the separation of PT income from ordinary income in TC (via PR #913).

Include PT income mtrs separately

---

btax/param_defaults/btax_defaults.json
btax/parameters.py

merged master into branch from #107

Jdebacker start_year

---

btax/calc_final_outputs.py
btax/calc_z.py
btax/get_taxcalc_rates.py
btax/param_defaults/btax_defaults.json
btax/parameters.py
btax/run_btax.py
btax/tests/test_params_have_effect.py
btax/util.py

This PR does 3 things:
1. Updates the starting year to 2017 and provides default values for parameters for all years 2015-2020 in the default parameters json.
2. Adds a boolean parameter to provide expensing for inventories.
3. Adds a boolean parameters to provide expensing for land.

Expense inventories

---

btax/calc_z.py
btax/parameters.py

This PR corrects the equation used to find the NPV of economic depreciation.

Fix economic depreciation

---

btax/calc_final_outputs.py
btax/run_btax.py

This PR fixes output frames so that they are not only sorted in the same order, but has the same indexes for each row.

Fix order or output dataframes

---

.travis.yml
btax/execute.py
btax/front_end_util.py
btax/pull_soi_corp.py
btax/pull_soi_partner.py
btax/pull_soi_proprietorship.py
btax/run_btax.py
btax/tests/test_params_have_effect.py
btax/util.py
conda.recipe/meta.yaml

test / build for Python 3

---

btax/execute.py
conda.recipe/meta.yaml

fix conda.recipe for BTAX_CUR_DIR

---

btax/calc_final_outputs.py
btax/parameters.py

The output variables for all investments were not calculated in the same way for the results by asset and by industry.  This fixes that.  The issue was with the calculation for the by industry table double counted some assets if they were also part of a major asset group.

Output by "All Investment"

---

btax/front_end_util.py
btax/tests/test_params_have_effect.py

This  PR makes the change advised by @hdoupe in a comment on PR #170.

Change outputs from json runner

---

btax/calc_final_outputs.py
btax/calc_z.py
btax/front_end_util.py
btax/param_defaults/btax_defaults.json
btax/parameters.py
btax/run_btax.py
btax/tests/test_params_have_effect.py

This PR makes the user defined parameters for expensing of inventories and land more flexible per the discussion in Web App Public [Issue #666](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/666).
Also include in this PR are some style changes to `parameters.py` and `calc_z.py` to become more PEP8 compliance and improve documentation.
This PR passed the pytest suite of tests, but the WIP label will remain until the model's output has been more closely verified.

Expensing of inventories and land

---

.travis.yml
btax/calc_final_outputs.py
btax/execute.py
btax/front_end_util.py
btax/get_taxcalc_rates.py
btax/parameters.py
btax/pull_soi_corp.py
btax/pull_soi_partner.py
btax/pull_soi_proprietorship.py
btax/read_bea.py
btax/run_btax.py
btax/soi_processing.py
btax/util.py

This PR updates the B-Tax scripts to meet (w/ some exceptions) PEP8 standards.  It also:
1) Puts the default start year in just one place.
2) Updates the `pd.DataFrame.ix()` to the correct `pd.DataFrame.loc()`
3) Makes commenting more clear.
I have confirmed that these stylistic changes have not affected any of the output.

Meet PEP8 standards

---

btax/run_btax.py

Change so don't load pickle twice

---

btax/get_taxcalc_rates.py
environment.yml

This PR updates B-Tax to be compatible with Tax-Calculator 0.15.0.
Note that B-Tax will not maintain compatibility with older version of TC.

Updates for tc 0.15.0

---

btax/calc_final_outputs.py
btax/tests/test_calc_final_outputs.py

This PR creates functions that compute the cost of capital and METRs, rather than including these calculations a larger function.
The PR will then
1) Add the user cost of capital to the output DataFrames
2) Add the tax wedge to the output DataFrames
2) Create unit tests of these new functions.

Functions for cost of capital, METR calculations

---

environment.yml

Needed one more package for B-Tax to run in the `btax-dev` environment.

Add xlrd to env

---

conda.recipe/meta.yaml

Try btax 0.0.0 in meta.yaml file.

change btax version

---

conda.recipe/bld.bat
conda.recipe/build.sh

This PR updates the `conda.recipe/bld.bat` and `conda.recipe/build.sh` as suggested in Issue #223.

Update scripts to build conda package

---

.travis.yml
environment.yml
setup.py

This PR updates the channel references for the tax calc package to PSLmodels.

Update conda channel from ospc to PSLmodels

---

MANIFEST.in

`MANIFEST.in` still not picking up all files...

Add xls BEA files

---

ccc/calculator.py

This PR adds a method to the `Calculator` class that allows one to save summary tables of results.

Table output

---

ccc/calculator.py
ccc/constants.py

Adds a table to show a summary of the distribution of assets by industry and tax treatment.

Asset table

---

conda.recipe/meta.yaml

Another change to try to get package to build...

Specify later version of paramtools

---

ccc/calculator.py
ccc/tests/test_calculator.py
ccc/utils.py

This PR adds tests for methods of the `Calculator` class, fixes an issue with the inclusion of inventories and land in overall calculations when they are dropped from disaggregated calcs, and adds a function to simply the saving of tables to disk.

Updates to Calculator class

---

compconfig/compconfig/functions.py

fix ref to html table

---

.readthedocs.yml
requirements.txt

This PR adds files to help configure the Sphinx build for ReadTheDocs.

add readthedocs files

---

ccc/default_parameters.json
docs/source/index.rst
setup.py

Changes depth of TOC in main sphinx doc, updates titles for COMP, adds sections for parameters on COMP.

Documentation updates

---

ccc/get_taxcalc_rates.py

This PR just helps to clarify the variables used in the computations of the marginal tax rate on pass-through income.  No results are affected.

Add more detail to comments about computing mtrs

---

ccc/utils.py
cs-config/cs_config/functions.py
cs-config/cs_config/tests/test_functions.py

This PR updates the dictionary keys that are used as the titles for groups of parameters on Compute Studio. 
There is also a change in font size for the html table output the results page.

Group names

---

ccc/parameters.py
ccc/paramfunctions.py
ccc/tests/test_paramfunctions.py

This PR adds more functions to compute parameters.  The idea is to make the code more modular and allow for easier testing of specific calculations of parameter values.

Add more parameter functions

---

ccc/calculator.py
ccc/utils.py
cs-config/cs_config/functions.py

This PR updates the bokeh plot output objects to work with the new Compute Studio API.

Bokeh updates for CS

---

cs-config/cs_config/functions.py

This PR reverts to the use of bokeh components for C/S output.

Change bokeh output

---

ccc/calculator.py
ccc/constants.py
ccc/tests/test_calcfunctions.py
ccc/tests/test_utils.py
ccc/utils.py

This PR adds tests of special cases of METRs and EATRs.  It also changes some calculator functions for tables and figures to allow the user to specify the marginal source of financing.  Finally, assertion statements are added to plot and table functions to ensure inputs are valid.

Additional units tests, output variables

---

ccc/data.py
ccc/tests/test_data.py
docs/source/data.rst

This PR adds unit tests for the methods in the `Assets` class in `data.py`.

Data tests

---

ccc/tests/test_utils.py
ccc/utils.py
environment.yml

This PR adds tests of the exceptions in functions in the `utils.py` module.

Unit tests for utils.py

---

ccc/parameters.py
ccc/tests/test_parameters.py

This PR adds unit tests to cover all lines of `parameters.py`.

Tests of parameters.py

---

.travis.yml
ccc/calculator.py
ccc/data.py
ccc/get_taxcalc_rates.py
ccc/parameters.py
ccc/tests/test_calculator.py
ccc/tests/test_data.py
ccc/tests/test_get_taxcalc_rates.py
docs/source/calculator.rst

This PR add unit tests to complete code coverage for `get_taxcalc_rates.py`

Add units tests for get_taxcalc_rates.py

---

cs-config/cs_config/functions.py

This PR updates the CS functions to be consistent with the bokeh plot data format needed by CS.

Change bokeh  data format for new CS release

---

ccc/constants.py
cs-config/cs_config/functions.py

This PR adds a title to the bokeh plot used in the C/S output.

Output plot

---

PSL_catalog.json

Minor JSON formatting change for PSL catalog builder
cc @jdebacker

PSL_catalog.json formatting

---

.github/workflows/deploy_sphinx.yml

This PR adds a GitHub Action yml to build and deploy sphinx docs

GitHub action 

---

docs/Makefile

add makefile for sphinx docs

---

PSL_catalog.json
README.md
docs/source/contributor_guide.rst

This PR updates the `README`, contributor guide, and PSL catalog for changes in how conda works, CCC version updates, and the GitHub pages link for documentation.

Updates for changes in conda, package versions, etc

---

.github/workflows/check_jupyterbook.yml
.github/workflows/deploy_jupyterbook.yml

This PR updates the miniconda setup (see [conda-incubator/setup-miniconda#101](conda-incubator/setup-miniconda#101)).

Update miniconda setup

---

docs/book/content/webapp.md

Add link to demo day video in docs

Add link to demo day video in docs

---

.github/workflows/build_and_test.yml
setup.py

This PR updates to build and test CCC on Python 3.9.

Update to build and teset on Python 3.9

---

citations.bib
cs-config/cs_config/helpers.py
docs/book/content/examples/PSL_demo.ipynb

This PR adds citations of CCC from March 2021 (and cleans up some import statements in a CS file).

Add March citations

---

cs-config/cs_config/helpers.py
cs-config/install.sh
docs/book/content/api/public_api.rst

This PR updates the `retrieve_puf` function used in the Compute Studio app to access the PUF.
cc @hdoupe

Update retrieve_puf function

---

README.md
docs/book/content/intro.md

Update version number for release of 1.2.8.

Update version number in docs

---

ccc/parameters.py
ccc/paramfunctions.py
ccc/tests/test_paramfunctions.py

This PR simplifies the functions calculating rates of return.

Simplify calculations of rate of return

---

README.md
ccc/calculator.py
setup.py

This PR prepares for release 1.2.9.  In addition, it changes `setup.py` to facilitate distribution of the package on PyPI.

New release, change setup.py for pip

---

.github/workflows/build_and_test.yml
README.md
ccc/calculator.py
citations.bib
conda.recipe/meta.yaml
environment.yml

This PR adds the following two references to the `citations.bib` file:
* Jason DeBacker and Richard W. Evans, "What Business Tax Reforms Would Be Best for Tennessee?" Research in Focus, Center for Growth and Opportunity at Utah State University, January 12, 2023, https://www.thecgo.org/research/what-business-tax-reforms-would-be-best-for-tennessee/
* Richard W. Evans, "What are the Effects of Missouri Corporate Income Tax Rate Cuts?" Research in Focus, Center for Growth and Opportunity at Utah State University, March 22, 2023, https://www.thecgo.org/research/what-are-the-effects-of-missouri-corporate-income-tax-rate-cuts/
cc: @jdebacker

Added two references to citations.bib

---

ccc/paramfunctions.py

Fix spacing for math to render

---

ccc/tests/test_calcfunctions.py
ccc/tests/test_calculator.py
ccc/tests/test_parameters.py
ccc/tests/test_run_ccc.py
ccc/utils.py
cs-config/cs_config/tests/test_functions.py
docs/book/content/examples/PSL_demo.ipynb

This PR updates the default start year to 2024.

Update model default start year

---

README.md
ccc/__init__.py
docs/book/content/intro.md
setup.py

This PR prepares version 1.4.0

Prepare Version 1.4.0
