btax/__init__.py, btax/param_defaults/btax_defaults.json, btax/param_defaults/btax_results_by_asset.json, btax/param_defaults/btax_results_by_industry.json, btax/parameters.py
This PR does some formatting on the jsons but does not change the content (just getting rid of multi line strings).  It also makes it possible to do:
`from btax import DEFAULTS`
and get the contents of `btax_defaults.json` as a Python object.
=> format jsons some, make defaults importable

btax/param_defaults/btax_results_by_asset.json, btax/param_defaults/btax_results_by_industry.json, btax/run_btax.py, btax/util.py, conda-requirements.txt
This PR changes `run_btax_to_json_tables` so that it does `run_btax` with no `user_params` (baseline), runs with `user_params`, then differences the two result sets.  The PR also changes the table column grouping names (under `table_id` in btax/param_defaults/btax_results_by*.json`).
=> Differencing (reform, baseline, delta)

btax/btax_reform_run.py, btax/calc_final_outputs.py, btax/calc_z.py, btax/data/depreciation_rates/Economic Depreciation Rates.csv, btax/parameters.py, btax/run_btax.py, btax/visuals.py
This PR cleans up the code - moving the saving of visual and tabular output to run_btax.run_btax_with_baseline_delta, which seems more appropriate.   It also fixes a set with copy warning and adds a script to run a particular reform (which can be used as an example for running other reforms locally).
Finally, some depreciation rates are updated to be more consistent with CBO numbers.
=> Clean up, Script to run particular reform

.travis.yml, btax/run_btax.py
Make PR #65 work with webapp-public by using keyword args instead of positional ones (`run_btax_to_json_tables`).
=> make optional args to json table creator function

.travis.yml, btax/param_defaults/btax_defaults.json, btax/parameters.py, btax/tests/test_params_have_effect.py, conda-requirements.txt
=> Fix ads gds tax

btax/run_btax.py, btax/tests/test_params_have_effect.py
There was an issue with shallow copies in the dictionary resulting in the reform being the same as baseline.  
The bug is shown here in @brendancol 's screenshot:
And with the fix:
=> fix shallow copy issue with tables

btax/tests/test_params_have_effect.py
Recently I added the test module `btax/tests/test_params_have_effect.py`.  This PR has some fixes to the slower running tests in there.  They were making some assertions that were not well-formed.  For example, sometimes a combination of parameters has to be changed before one parameter's effects can be seen.  
Work in progress - do not merge yet.
=> fixes to make tests valid

btax/calc_z.py, btax/parameters.py
After reading [this paper](http://www-personal.umich.edu/~shapiro/bonus-depreciation.pdf) by Shapiro, I noticed the difference between metrs with and without bonus were too large.  After some investigation, I found that calc_z was not correctly handling bonus depreciation. 
This pull request corrects the calculation of the NPV of depreciation deductions in the presences of bonus.
=> Fix equation to determine bonus depreciation

btax/check_asset_alloc.py, btax/data/raw_data/soi/soi_partner/13pa05_Crosswalk.csv, btax/param_defaults/btax_defaults.json, btax/parameters.py, btax/pull_soi_corp.py, btax/pull_soi_partner.py, btax/pull_soi_proprietorship.py, btax/read_bea.py, btax/run_btax.py, btax/soi_processing.py, btax/util.py
This PR splits partner assets between corporate and non-corporate partners.
It also adds a script to help check:
1) That asset totals match BEA totals
2) That assets are distributed between corporate and non-corporate entities in a reasonable way.
=> Split assets by type of partner

btax/parameters.py
This PR fixes a bug affecting the after tax rate of return for non-corporate entities in the case that they face no entity level tax, but there is a denial of interest for deductibility at the entity level.
=> Fix bug in treatment of interest deductibility for pass-throughs

btax/calc_final_outputs.py, btax/parameters.py
This PR fixes the calculation for the cost of capital for inventory investment.  Inventories are handled differently than depreciable assets and so the cost of capital calculation is made separately for these assets.
=> Update cost of capital calculation for inventories

btax/calc_final_outputs.py, btax/param_defaults/btax_results_by_asset.json, btax/param_defaults/btax_results_by_industry.json, btax/parameters.py, btax/read_bea.py, btax/run_btax.py
This PR adds to the output by asset and industry calculations of the METRs (and other variables) by major asset/industry group and a rate for all investments.
There is also an update to fix some typos in the default json files.
This is  a WIP at the moment - the industry groupings aren't working because the industry names have some strange characters due to some encoding issue.  Therefore the industries aren't being matched to their major groups.
In addition, I don't know if this will pass the column tests since this PR adds columns.
There is also some issue when creating the differences between the baseline and reform by industry, I think due to the additional column being a string.  Will need to update this difference function in util.py to accommodate.
=> Add major groups

btax/parameters.py
David Brazell pointed out an odd result for the METRs on pass-through investment under full expensing and interest non-deductibility. In this case, the METR should be non-negative.  The cause was a an incorrect line of code specifying how interest haircuts worked on PTs.  This PR fixes that.
=> Fix interest deductibility for PTs

btax/param_defaults/btax_defaults.json, btax/parameters.py
This PR allows B-Tax to utilize any start year from 2015-2020 (although the dependency on Tax-Calculator will only allow 2015-2017).
=> Allow flexible start year

btax/run_btax.py
This PR reverts the name of `execute.py` back to `run_bax.py`.  The purpose is to make updating of the B-Tax worker notes for TaxBrain work more smoothly (in the future, we'll update everything with the new filename).
=> Revert file name

btax/calc_z.py, btax/data/depreciation_rates/tax_depreciation_rates.csv, btax/parameters.py
This PR fixed the null results reported when the ADS depreciation system is selected.  The error was the result of a incorrect reference to a data frame element.  This has been fixed and results appear ok.
=> Fix ADS depreciation errors

btax/calc_final_outputs.py, btax/get_taxcalc_rates.py
This PR does 2 things:
1) Sorts the final tables of output.  This corrects some errors when differencing tables.
2) Makes B-Tax compatible with Tax Calc 0.7.7 by removing the passing of growth assumptions which was unused anyway.
=> Fix sorting on final tables

btax/parameters.py
This PR implements alternative assumptions about the after tax rate of return for investors in non-corporate businesses in the case of an entity level tax on these businesses.
In particular,  it assumes the the ratio of debt and equity used to finance investments remains that seen historically amongst non-corporate businesses (rather than what is seem amongst corporate businesses).
This does not fix any bug, but merely implements an alternative assumption.  No rush on deploying this.
=> Modify pass through entity tax assumptions

conda.recipe/meta.yaml
Fix B-Tax numpy and pandas versions to be like `taxcalc=0.8.4` - See also [Tax-Calculator Issue 
31](https://github.com/open-source-economics/policybrain-builder/issues/31)
=> fix numpy and pandas versions

btax/pull_soi_partner.py, btax/pull_soi_proprietorship.py
This PR changes calls to the data frame method `reset_index` so as to be consistent with Pandas 0.20.0.  
The `asset_data.pkl` file is also updated to be consistent with the new Pandas version.
=> Make consistent with Pandas 0.20.0

btax/execute.py, btax/run_btax.py
This PR comments out the import of `visuals.py` and `visuals_plotly.py`.  The are scripts that are inactive, but will be left in as a placeholder for the work of @DoraSzasz.  Commenting these out helps avoid the need to import bokeh.
Also in the PR  the `asset_data.pkl` file is updated to conform to pickle with Python 3.x
=> Comment out visuals.py import

btax/front_end_util.py, btax/tests/test_params_have_effect.py
This PR updates `btax.front_end_util.runner_json_tables()` to pass all data frames in a serialized format.
=> Pass all dataframes in serialized format

conda.recipe/meta.yaml
This PR updates the `meta.yaml` file to pin the Tax-Calculator version used when created the B-Tax conda package.
=> Pin taxcalc version

btax/calc_final_outputs.py, btax/parameters.py, btax/tests/test_calc_final_outputs.py
This PR added Devereux-Griffith (1998) Effective Average Tax Rate (EATR) calculations are part of the B-Tax output.
The PR also adds the "tax wedge" (computed as the difference between the before tax rate of return and the required after-tax rate of return).
=> Add EATR calculations

btax/get_taxcalc_rates.py, btax/parameters.py, btax/run_btax.py, btax/util.py
This PR allows B-Tax to read in the CPS file as the micro data used by Tax-Calculator.
One major issue to resolve before this can be merged - it seems that the capital gains variable is missing from the CPS.  This is needed to compute MTRs on capital gains income, an input into the METTR computed by B-Tax.
=> [WIP] CPS as microdata

.travis.yml, btax/tests/test_4package.py, conda.recipe/meta.yaml, environment.yml
This PR updates the `meta.yaml` file used to build the B-Tax package so that it properly specifies how to determine the package version.  This error was pointed out by @martinholmer in Issue #221.  
The `meta.yaml` file also simplifies package dependencies as noted in [this comment](https://github.com/open-source-economics/Behavioral-Responses/pull/18#issue-228848719).
=> Updates to meta.yaml

btax/parameters.py
This PR removes reference to the `B-Tax/btax/tests_data/cps*` files.
=> Use CPS files that are in Tax-Calculator

ccc/get_taxcalc_rates.py, ccc/tests/test_get_taxcalc_rates.py
This PR adds test coverage for the functions in `get_taxcalc_rates.py` and adds a loop to make more efficient the code to compute marginal tax rates.
=> Tests and reduction of code for get_taxcalc_rates.py

.coveragerc, .gitignore
Correct mistake in PR #263 that causes the project code-line count to include not only the lines of code in the `ccc` directory (which is correct), but also the lines of code in the `ccc/tests` directory (which is incorrect).
A coverage statistic is supposed to say what fraction of the project's code (in `ccc`) is tested by the pytest suite in `ccc/tests`.  My mistake in PR #263 was to forget to do `git add .coveragerc` before the last commit.  This pull request fixes that mistake.
Note that the GitHub coverage test "failed" because this change (correctly) lowers the coverage rate by a couple percent.  Here is what the incorrect coverage report looked like for PR #266.
Now after the changes in this PR, the project code-line count is only 1070 because the lines of code in `ccc/tests` have …
=> Add .coveragerc file so tests are not included in code line count

.travis.yml, ccc/calcfunctions.py, ccc/calculator.py, ccc/get_taxcalc_rates.py, ccc/parameters.py, pytest.ini, setup.cfg
This pull request shows how to run the PEP8 code-style checks automatically for each GItHub check-in.  
It also shows how to use the `pep8ignore` directive in the new `pytest.ini` file to customize the nature of the PEP8 testing by file.
I didn't know enough about the Sphinx LaTeX equations in `calcfunctions.py`file.  If the equations can be continued on a second or third or fourth line, then they could be reformatted and the `ccc/calcfunctions.py E501` line in the `pytest.ini` file could be removed.
=> Activate PEP8 testing for each GitHub check-in

compconfig/install.sh
This PR updates the `compconfig/install.sh` script so that CCC is installed using conda instead of pip installing the package from the git repository.
=> Use conda instead of pip install from repo

docs/source/public_api.rst
Try to improve formatting of sphinx docs.
=> use depth of 1 for toc tree

compconfig/install.sh, conda.recipe/meta.yaml, environment.yml, setup.py
This PR updates the package building files to specify the bokeh must be at least version 1.2.  Previously, CCC relied on TC's bokeh version, but TC specifies bokeh version 0.13 or greater and sometimes conda installs that version and not the newest.  This PR resolved such issues.
=> Bokeh dependency

compconfig/compconfig/functions.py, compconfig/compconfig/tests/test_functions.py
The COMP `run_model` function was using the `adjust` method and not the `update_specification` method and therefore parameter updates were not being properly reflected.  This PR fixes that bug and adds a test to verify changes in parameters produce changes in output.
=> Fix bug in COMP functions

ccc/default_parameters.json, cs-config/cs_config/functions.py, environment.yml
This PR filters the parameters on CS that should remain constant between the baseline and reform.
The PR also adds more to the description of the interest deduction haircut parameter to note how current law is handled (per Issue #285).
=> Parameters for CS

conda.recipe/meta.yaml, environment.yml
In preparing [Tax-Calculator #2391](https://github.com/PSLmodels/Tax-Calculator/pull/2391), I found that Bokeh introduced the `legend_label` attribute (used in a few methods in `ccc/calculator.py`) in v1.4.0
cc @jdebacker
=> Bump Bokeh requirement to 1.4.0

ccc/data.py
This PR updates the path to `ccc_asset_data.csv` in the kwargs of the `Assets` class so that this file can be found without one having to build the `ccc` package.
=> Path to ccc_asset_data.csv

.coveragerc, cs-config/cs_config/functions.py, cs-config/cs_config/inputs.py, cs-config/cs_config/tests/test_functions.py, pytest.ini
This PR adds more output to the Compute Studio app for CCC.  The output page will now include 3 plots and one table.  The download will not have 3 csv files so that users can have the most detailed output from the model to look at changes by industry and asset.
=> Add more output to C/S app

PSL_catalog.json
This PR updates links to CCC documentation on the [PSL Catalog page](https://www.pslmodels.org/Catalog/index.html).
=> PSL catalog links

cs-config/install.sh
@jdebacker This should fix this error:
```
______________________ ERROR collecting test_functions.py ______________________
ImportError while importing test module '/home/test_functions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
test_functions.py:5: in <module>
from cs_config import functions
/opt/conda/lib/python3.7/site-packages/cs_config/__init__.py:1: in <module>
from .functions import *
/opt/conda/lib/python3.7/site-packages/cs_config/functions.py:14: in <module>
from cs2tc import convert_policy_adjustment
E   ModuleNotFoundError: No module named 'cs2tc'
```
=> Add cs2tc to cs-config/install.sh

ccc/get_taxcalc_rates.py, cs-config/cs_config/tests/test_functions.py
This adds a simple check to determine if the Tax-Calculator reform is using the ParamTools format.
Similar to this Tax-Brain code: https://github.com/PSLmodels/Tax-Brain/blob/ba0ab07b6dd4f3c35097bada595cd7b82cf874a9/taxbrain/utils.py#L160-L196
=> Check if reform is paramtools or tc style

cs-config/cs_config/functions.py
This PR adds a filter so that not all the CCC parameters are available on the C/S web app.  The reason is two-fold:
1) Some of the individual income tax rate parameters are redundant on the app since Tax-Calculator is run in each C/S run.
2) Some parameters, such as those around household savings behavior, are too "in the weeds" and unlikely to be changed by C/S users.  Removing them will reduce clutter and confusion on the C/S input page.
=> Filter CCC params for C/S

cs-config/cs_config/functions.py
This PR updates the start year for CS to allow one to start in 2013 if using the PUF and 2014 if using the CPS.
=> update start year for CS

cs-config/cs_config/functions.py, cs-config/cs_config/tests/test_functions.py, environment.yml
This PR adds logic to validate the start year conditional on the dataset chosen in the C/S web application.  A test of this logic is also added.
=> CS year validator

requirements.txt
This PR removes the `requirements.txt` file since it is no longer used. I noticed this when building a new version of the CCC app for Compute Studio.
=> Delete no longer used `requirements.txt` file

cs-config/install.sh
This installs `ccc` from conda-forge instead of the pslmodels conda channel.
=> Install ccc from conda-forge on Compute Studio

ccc/calcfunctions.py, ccc/tests/test_calcfunctions.py
A cost of capital that is non-positive does not make sense (the result would be infinite profits through infinite investment).  This PR adds a `RuntimeError` that is raised if the parameters used result in a non-positive cost of capital.
cc @hdoupe -- this addresses a recent error seen in Compute Studio.
=> Add exception for non-positive cost of capital

cs-config/cs_config/helpers.py, environment.yml
This PR makes a couple modifications for the `cs-config` files to work with the lates `cs-kit`.
@hdoupe -- It looks like the latest `cs-kit` will fix the `bokeh` plot rendering issues on C/S:
```
cs_kit.exceptions.CSKitError: "Bokeh outputs must be created with json_item. Reference: https://docs.compute.studio/publish/outputs/#bokeh"
```
Is that correct?
=> Updates for new cs kit

ccc/calculator.py, ccc/controls_callback_script.py, ccc/default_parameters.json, ccc/get_taxcalc_rates.py, ccc/parameters.py, ccc/paramfunctions.py, ccc/tests/test_parameters.py, ccc/tests/test_paramfunctions.py, docs/book/content/CCC_guide.md
This PR attempts to improve variable name consistency by replacing `nc` with `pt` and `corp` with `c`.
=> Improve variable and parameter name consistency

ccc/tests/test_utils.py, cs-config/cs_config/functions.py, cs-config/cs_config/helpers.py, cs-config/install.sh, data/soi_processing.py, environment.yml
This PR updates the s3 bucket used for data on the C/S app.
The version of Pandas is also pinned in the env to ensure things work as expected.
=> Updates for C/S app

ccc/calculator.py
https://docs.bokeh.org/en/latest/docs/releases.html
=> Fix warning from using deprecated method with size argument

.github/workflows/build_and_test.yml, README.md, ccc/__init__.py, ccc/get_taxcalc_rates.py, ccc/parameters.py, ccc/tests/test_get_taxcalc_rates.py, ccc/tests/test_start_years.py, cs-config/cs_config/functions.py, cs-config/cs_config/helpers.py, cs-config/cs_config/tests/test_functions.py, docs/book/content/intro.md, pytest.ini, setup.py
This PR update `get_taxcalc_rates.py` to allow for more flexibility in the micro data file used by allowing for grow factors, weights, and start years to be passed as arguments.
=> Allow for more flexibility in individual income tax micro data input

README.md, ccc/__init__.py, ccc/calculator.py, docs/book/content/intro.md, environment.yml, pyproject.toml, setup.py
This PR updates `setup.py` to build the package in a way that works with distribution to PyPI.  A `pyproject.toml` file is also added due to updates to how editable packages can be built (see `pip` [Issue #11457](https://github.com/pypa/pip/issues/11457) for more on this).
=> Updates to `setup.py`

.github/workflows/create_pip_package.yml, README.md, ccc/__init__.py, ccc/calcfunctions.py, ccc/calculator.py, ccc/constants.py, ccc/parameters.py, ccc/tests/test_start_years.py, ccc/utils.py, docs/book/content/intro.md, setup.py
This PR fixed some errors arising from deprecated packages (namely, `pkg_resources`) and methods (e.g., the behavior of the `replace` method on Pandas DataFrames.
=> Updates to deprecated commands

ccc/calcfunctions.py, docs/book/content/CCC_guide.md
This PR cleans up unnecessary lines from `calcfunctions.py` and fixes various typos in the documentation.
=> Clean up `calcfunctions.py` and docs

docs/book/content/CCC_guide.md
This PR fixes typos in some equations in the CCC guide.
=> Fix typos in docs
